project:
  type: website
  output-dir: docs
website:
  title: "ABL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: people.qmd
        text: People
     

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



